# Servidor
server.port=8080
spring.application.name=api-gateway
# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# JWT Secret (mismo que ms-users, pedir a Alejandro)
jwt.secret=${JWT_SECRET:claveSecretaSuperSeguraParaJWTdeAlMenos64CaracteresDeberiaSerMasLarga123456}
# Rutas a microservicios
#ms-users
spring.cloud.gateway.routes[0].id=ms-users
spring.cloud.gateway.routes[0].uri=lb://ms-users
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
#ms-catalog
spring.cloud.gateway.routes[1].id=ms-catalog
spring.cloud.gateway.routes[1].uri=lb://ms-catalog
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/productos/**
#ms-suppliers
spring.cloud.gateway.routes[2].id=ms-suppliers
spring.cloud.gateway.routes[2].uri=lb://ms-suppliers
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/proveedores/**
#ms-inventory
spring.cloud.gateway.routes[3].id=ms-inventory
spring.cloud.gateway.routes[3].uri=lb://ms-inventory
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/inventario/**
#ms-audit
spring.cloud.gateway.routes[4].id=ms-audit
spring.cloud.gateway.routes[4].uri=lb://ms-audit
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/auditoria/**
