server:
  port: 8081
  error:
    include-message: always

spring:
  application:
    name: ms-users
  
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_users?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    template:
      exchange: ""
      routing-key: ${RABBITMQ_QUEUE_MAIL:cola.mails}
    queues:
      mail: ${RABBITMQ_QUEUE_MAIL:cola.mails}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

# Configuración personalizada para JWT (usará el .env)
jwt:
  secret: ${JWT_SECRET:e5355151e2589d2b316e10af29ba6463e6fbcc836cd626cad9715541109ad707fdbfce4f0176a19235956075714b9c0937e882ce08c8885584d42705c0ebaab7}
  expiration: ${JWT_EXPIRATION_MS:3600000}

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5500}
