#server
server.port=8761
#server eureka client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
#server eureka server
eureka.server.enable-self-preservation=false
#spring application name
spring.application.name=eureka-server


